### ISSUE TITLE
API

### ISSUE THREAD

**Issue by JDias** [Plataformas-Cidadania/portalosc#4]
Olá,
Estou tentando acessar a API, existe algum lugar com um código exemplo?

o endpoint seria esse?
https://www.mapaosc.ipea.gov.br:8383/api

(está dando timeout para mim)

**Comment by EricFerreiraS** [comment]
Olá,
No momento não existe endpoint para acesso direto a API. Estamos trabalhando em uma forma mais amigável para o download das informações. Continue acompanhando o site para ficar sabendo das novidades.
