### ISSUE TITLE
Dúvida: O mongodb está sendo utilizado?

### ISSUE THREAD

**Issue by sfelix-martins** [Plataformas-Cidadania/portalosc#7]
E aí, blz?

Ao instalar o projeto no meu ambiente local foi necessário instalar o mongodb e o driver do mongodb para php para que o composer pudesse instalar as dependências corretamente.

Porém não consegui identificar o local onde o mongodb está sendo utilizado.

**Comment by EricFerreiraS** [comment]
Olá,
 O uso do mongodb ainda está em fase de testes. Ele será o local de armazenamento dados que os estados e municípios enviariam para o nosso sistema.
